<?php require __DIR__ . '/includes/site.php'; abg_head('Contact Us | ABGTECH', 'Contact ABGTECH for software development, product demos, and digital marketing support.'); abg_nav('contact'); ?>
<header class="page-hero">
  <div class="container hero-content">
    <div class="breadcrumb-soft"><a href="index.php">Homepage</a><i class="bi bi-chevron-right"></i><span>Contact Us</span></div>
    <div class="row align-items-center g-5">
      <div class="col-lg-7 reveal"><span class="eyebrow"><i class="bi bi-chat-dots"></i> Contact Us</span><h1 class="display-title mt-4 mb-4">Tell us what you want to build or grow.</h1><p class="lead-copy">Use the form below for software projects, product demos, and digital marketing campaigns.</p></div>
      <div class="col-lg-5 reveal"><div class="premium-card p-4 text-dark"><h2 class="h4 fw-bold">Contact Info</h2><p class="section-copy mb-1">Email: info@abgtech.co</p><p class="section-copy mb-1">Phone: +256 700 000 000</p><p class="section-copy mb-0">Location: Kampala, Uganda</p></div></div>
    </div>
  </div>
</header>
<section class="section"><div class="container"><div class="row g-5"><div class="col-lg-5 reveal"><div class="section-kicker">Lead Capture</div><h2 class="section-title">A smarter project intake form.</h2><p class="section-copy">Select your interest, timeline, and project notes so ABGTECH can route your request to the right team.</p></div><div class="col-lg-7 reveal"><div class="premium-card p-4"><form class="row g-3" data-lead-form><div class="col-md-6"><label class="form-label fw-bold">Full name</label><input class="form-control form-control-lg" required placeholder="Your name"></div><div class="col-md-6"><label class="form-label fw-bold">Email</label><input type="email" class="form-control form-control-lg" required placeholder="you@example.com"></div><div class="col-md-6"><label class="form-label fw-bold">Interest</label><select class="form-select form-select-lg" required><option value="">Select one</option><option>Custom Software Development</option><option>Digital Marketing</option><option>Sacco & Microfinance System</option><option>School Management System</option><option>Retail POS & Inventory System</option><option>Medical Clinic & Pharmacy System</option></select></div><div class="col-md-6"><label class="form-label fw-bold">Timeline</label><select class="form-select form-select-lg" required><option value="">Select timeline</option><option>Immediately</option><option>This month</option><option>1-3 months</option><option>Planning ahead</option></select></div><div class="col-12"><label class="form-label fw-bold">Project notes</label><textarea class="form-control form-control-lg" rows="5" placeholder="Briefly describe your goals"></textarea></div><div class="col-12"><button class="btn btn-premium btn-lg w-100" type="submit">Submit Request</button></div><div class="col-12"><div class="alert alert-success d-none mb-0" data-form-message>Thank you. Your request is ready for the ABGTECH team.</div></div></form></div></div></div></div></section>
<?php abg_footer(); ?>
