<?php require __DIR__ . '/includes/site.php'; abg_head('Sacco & Microfinance System | ABGTECH', 'ABGTECH Sacco and Microfinance System for savings, shares, loans, repayments, reports, and compliance.'); abg_nav('products'); ?>
<header class="product-hero">
  <div class="container hero-content">
    <div class="row align-items-center g-5">
      <div class="col-lg-6 reveal"><div class="breadcrumb-soft"><a href="index.php">Homepage</a><i class="bi bi-chevron-right"></i><a href="products.php">Products Page</a></div><span class="eyebrow"><i class="bi bi-bank"></i> Sacco & Microfinance System</span><h1 class="display-title mt-4 mb-4">The all-in-one platform for Saccos, VSLAs, and MFIs.</h1><p class="lead-copy">Manage members, savings, shares, loans, repayments, and reports in one secure system built for financial accountability.</p><div class="d-flex flex-column flex-sm-row gap-3"><a class="btn btn-premium" href="contact.php">Request Demo</a><a class="btn btn-ghost" href="contact.php">Download Brochure</a></div></div>
      <div class="col-lg-6"><div class="hero-mock"><div class="mock-window"><div class="mock-top"><span></span><span></span><span></span></div><div class="p-4"><div class="row g-3 mb-3"><div class="col-7"><div class="metric-tile"><small>Total Savings</small><h3 class="fw-bold text-primary">UGX 428M</h3></div></div><div class="col-5"><div class="metric-tile"><small>Loan Status</small><span class="badge-soft badge-green d-inline-block mt-2">Approved</span></div></div></div><table class="table table-soft"><tbody><tr><td>Sarah N.</td><td>UGX 2.4M</td><td><span class="badge-soft badge-green">Active</span></td></tr><tr><td>David K.</td><td>UGX 980K</td><td><span class="badge-soft badge-amber">Review</span></td></tr><tr><td>Mary A.</td><td>UGX 4.1M</td><td><span class="badge-soft badge-green">Active</span></td></tr></tbody></table></div></div></div></div>
    </div>
  </div>
</header>
<section class="section"><div class="container"><div class="text-center mx-auto mb-5 reveal" style="max-width:850px;"><div class="section-kicker">Problem Statement</div><h2 class="section-title">Managing a Sacco manually leads to costly gaps.</h2></div><div class="row g-4 mb-5"><?php foreach ([['bi-exclamation-triangle','Inaccurate records'],['bi-hourglass-split','Late loan approvals'],['bi-file-lock','No audit trail']] as $p): ?><div class="col-md-4 reveal"><div class="premium-card p-4 h-100"><i class="bi <?= $p[0] ?> fs-1 text-danger"></i><h3 class="h4 fw-bold mt-3"><?= $p[1] ?></h3><p class="section-copy">Manual processes slow decisions and make accountability difficult.</p></div></div><?php endforeach; ?></div><div class="cta-banner reveal text-center"><h2 class="h1 fw-bold">ABGTECH Sacco System solves this with structured records, workflows, and reports.</h2></div></div></section>
<section class="section section-dark"><div class="container"><div class="text-center mx-auto mb-5 reveal" style="max-width:850px;"><div class="section-kicker">Core Features</div><h2 class="section-title">Interactive feature modules for finance teams.</h2></div><div class="tab-shell overflow-hidden text-dark reveal" data-tabs><div class="tab-buttons"><?php foreach (['members'=>'Member Management','savings'=>'Savings & Shares','loans'=>'Loan Processing','reports'=>'Reports & Compliance'] as $k=>$v): ?><button class="tab-btn <?= $k==='members'?'active':'' ?>" data-tab="<?= $k ?>"><?= $v ?></button><?php endforeach; ?><span class="tab-indicator"></span></div><?php $tabs=['members'=>['Member records, KYC details, group structures, guarantors, and status tracking.',['Member profiles','KYC documents','Group membership','Guarantor links','Member activity logs']], 'savings'=>['Savings and share balances with deposits, withdrawals, dividends, and statement history.',['Savings deposits','Share purchases','Withdrawals','Dividend records','Member statements']], 'loans'=>['Loan applications, approval workflows, repayment schedules, arrears, and guarantor checks.',['Loan requests','Approval levels','Repayment schedules','Penalty tracking','Arrears reports']], 'reports'=>['Management reports, audit trails, branch summaries, and compliance-ready exports.',['Portfolio reports','Audit trail','Branch performance','Exportable statements','Role-based reports']]]; foreach($tabs as $key=>$tab): ?><div class="tab-panel p-4 <?= $key==='members'?'active':'' ?>" data-panel="<?= $key ?>"><div class="row align-items-center g-4"><div class="col-lg-7"><h3 class="h2 fw-bold"><?= $tab[0] ?></h3><ul class="section-copy fs-5"><?php foreach($tab[1] as $li): ?><li><?= $li ?></li><?php endforeach; ?></ul></div><div class="col-lg-5"><div class="metric-tile text-center"><i class="bi bi-bank fs-1 text-primary"></i><h4 class="fw-bold mt-3">Finance control center</h4></div></div></div></div><?php endforeach; ?></div></div></section>
<section class="section"><div class="container"><div class="row g-4"><?php foreach ([['bi-diagram-3','Automated loan approval workflows'],['bi-chat-dots','SMS & email member notifications'],['bi-buildings','Multi-branch support'],['bi-wifi-off','Offline-capable workflows'],['bi-person-lock','Role-based access'],['bi-file-earmark-check','Compliance-ready reports']] as $b): ?><div class="col-md-6 col-lg-4 reveal"><div class="premium-card p-4 h-100"><div class="icon-box mb-3"><i class="bi <?= $b[0] ?>"></i></div><h3 class="h5 fw-bold"><?= $b[1] ?></h3></div></div><?php endforeach; ?></div></div></section>
<section class="section pt-0"><div class="container"><div class="premium-card p-4 reveal"><h2 class="h1 fw-bold mb-4">System modules visual</h2><div class="module-map"><div class="module-node">Members</div><div class="module-node">Loans</div><div class="module-node">Repayments</div><div class="module-node">Reports</div></div></div></div></section>
<section class="section pt-0"><div class="container"><div class="row g-4 mb-5"><?php foreach (['Starter','Growth','Enterprise'] as $tier): ?><div class="col-md-4 reveal"><div class="premium-card p-4 h-100"><h3 class="h2 fw-bold"><?= $tier ?></h3><p class="section-copy">Contact us for pricing based on branches, members, modules, and support needs.</p><a class="btn btn-premium w-100" href="contact.php">Request Pricing</a></div></div><?php endforeach; ?></div><div class="cta-banner reveal d-flex flex-column flex-lg-row gap-4 align-items-lg-center justify-content-between"><div><h2 class="section-title mb-2">See the Sacco System live.</h2><p class="text-white-50 mb-0">Book a free demo for your board or management team.</p></div><a class="btn btn-light btn-lg fw-bold" href="contact.php">Book Demo</a></div></div></section>
<?php abg_footer(); ?>
